# Generated by Django 2.0.5 on 2018-05-05 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20180505_2027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_time']},
        ),
        migrations.AddField(
            model_name='comment',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
