# Generated by Django 2.0.5 on 2018-05-05 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_auto_20180505_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='views',
        ),
    ]
